import type { NextPage } from 'next';
import Head from 'next/head';

import PieChart from './components/PieChart';
import {
  ChartContainer,
  MainContainer,
  PageTitle,
} from './components/PageUtils';
import { ChartKey, ChartOperator } from '../enums/Chart';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Bmw Charts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MainContainer>
        <PageTitle>📈 Gráficos de vendas da BMW</PageTitle>
        <ChartContainer>
          <PieChart
            chartKey={ChartKey.FUEL_TYPE}
            operator={ChartOperator.EQUAL}
            price={10000}
          />
          <PieChart
            chartKey={ChartKey.TRANSMISSION}
            operator={ChartOperator.LESS_THAN}
            price={20000}
          />

          <PieChart
            chartKey={ChartKey.MODEL}
            operator={ChartOperator.EQUAL}
            price={20000}
          />
          <PieChart
            chartKey={ChartKey.YEAR}
            operator={ChartOperator.EQUAL}
            price={30000}
          />
        </ChartContainer>
      </MainContainer>
    </>
  );
};

export default Home;
